name: 本机工具安装
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lifecycle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87
        with:
          toolchain: nightly-2026-05-25
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24
      - run: cargo test --locked -p az-tool --features native
      - run: cargo clippy --locked -p az-tool --features native --all-targets -- -D warnings
